dbt_airbnb_project:
  outputs:
    dev:
      account: **************
      database: AIRBNB
      password: *************
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: ANSHLAMBA
      warehouse: COMPUTE_WH
  target: dev
